# -*- coding: utf-8 -*-
"""QualityControlToMaster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RHvThEpDuLOmiQOlNC0gwLDU9sftiZrm
"""

import csv
import collections
import pandas as pd
iteration = 1


def main():
    master_data = pd.read_csv(f'MASTER_{iteration}.csv')
    qc_data = pd.read_csv('QC_MODULE_OUTPUT.csv')

    story_cons = dict()  # (ref_story, ref_decision) -> (HitId, input, decision1, decision2)

    for i, row in qc_data.iterrows():
        ref_story = row["Referring_Story_Id"]
        ref_dec = int(row["Referring_Decision"])
        hit_id = row["HitId"]
        input = row["Input"]
        dec_1 = row["Decision_1"]
        dec_2 = row["Decision_2"]

        story_cons[(ref_story, ref_dec)] = (hit_id, input, dec_1, dec_2)

    # Add new data to master_data dataframe
    for (ref_story, ref_dec), (hit_id, input, dec_1, dec_2) in story_cons.items():
        df = pd.DataFrame({"HitId": [hit_id],
                           "Text": [input],
                           "Decision1": [dec_1],
                           "Decision2": [dec_2],
                           "Referring_Story_Id": [ref_story],
                           "Referring_Decision": [ref_dec]
                           })

        master_data = master_data.append(df, ignore_index=True)

    master_data.to_csv(f'MASTER_{iteration}.csv', index=False)


if __name__ == '__main__':
    main()
